# Site settings
title: Steve's Pictures
email: "steve@stevegamble.com"
description: "Photo Journal"
url: "https://www.stevegamble.com"
baseurl: "/gallery"
facebook_username: "steve.gamble.900"
#twitter_username: ""
instagram_username: "a_stevegamble"
github_username:  "stevegamble"
#deviantart_username: ""
#flickr_username: ""
#discus_shortname: ""
strava_username: "stevegamble"
linkedin_username: "stevegamble"
share: true

# Owner/author information
owner:
  name:   Steve Gamble
  avatar: avatar.png
  favicon: favicon.ico
  info: photography website template

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from

whitelist:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from

# Settings for comments helper
# Set 'provider' to the comment provider you want to use. (i.e.  Disqus, Intense Debate, livefyre, or Facebook Comments)
# Set 'provider' to false to turn commenting off globally.
#Set 'provider: false' to disable comments globally.
# Disable comments for individual pages/posts by specifying 'comments: false' in the page/post YAML Front Matter.
#
comments :
  provider : false
  disqus :
    short_name : ""

# Internal nav
nav:
  - HOME: "/gallery"
  - GALLERY: "/gallery/gallery"  
#  - JOURNAL: "/journal/"
#  - ABOUT: "/about/"

# All translation keys
translations:
 # 404.html
  permalink: "/404.html"

# Server
destination:      	 ./_site
port:             	 4000


# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
paginate_path: "/journal/page:num/"
permalink: "/journal/:title/"
categories_path: "/journal/category/"
tags_path: "/journal/tag/"
gems: 
 - jekyll-paginate
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# SiteMap
sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/atom.xml"
        - "/feed.xml"
        - "/feed/index.xml"
    include_posts:
        - "/writing/"
    change_frequency_name: "change_frequency"
    priority_name: "priority"
